name: Android CI (Unit Tests)

on:
  # Triggers the workflow on push or pull request events for the main and develop branches
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit_test:
    # Use a standard Linux runner environment
    runs-on: ubuntu-latest

    # Define the environment variables used by the Android SDK
    env:
      JAVA_VERSION: '17'
      # The problematic line for ANDROID_SDK_ROOT is removed here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Cache
        # Action to cache Gradle dependencies, speeding up subsequent builds
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      # --- NEW STEP TO FIX ANDROID SDK PATH ---
      - name: Set ANDROID_SDK_ROOT Environment Variable
        run: echo "ANDROID_SDK_ROOT=$HOME/Android/sdk" >> $GITHUB_ENV

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        # Executes the 'testDebugUnitTest' task, which runs all tests
        run: ./gradlew testDebugUnitTest

      - name: Publish Test Report (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/debug/
          retention-days: 7

      - name: Build Debug APK (Optional - useful for checking build validity)
        run: ./gradlew assembleDebug
